"""Demo capture service — records pipeline artifacts for reproducible demos.

Enabled only when CONFIDOC_DEMO_CAPTURE=true.
All write/log calls are silent no-ops when demo capture is disabled or when
the given job_id has no active demo run.

Security contract
─────────────────
• safe_display fields in entity_events.jsonl use stable tokens ([PATIENT_NAME_001])
  or label strings — never raw PHI text.
• entity_events.public.jsonl (generated by make_public_events) strips the
  safe_display field too and keeps only structural metadata.
• No mapping files, no original PHI, no source PDFs enter Zone 2 paths.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

_TOKEN_RE = re.compile(r'\[[A-Z][A-Z_]*_\d{3}\]')


# ── Internal helpers ──────────────────────────────────────────────────────────

def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _sha256_path(path: Path) -> str:
    return _sha256_bytes(path.read_bytes())


def _settings():
    from app.config import settings
    return settings


def _enabled() -> bool:
    return _settings().demo_capture


# ── Session registry ──────────────────────────────────────────────────────────

def _sessions_path() -> Path:
    s = _settings()
    s.demo_runs_dir.mkdir(parents=True, exist_ok=True)
    return s.demo_runs_dir / "sessions.json"


def _load_sessions() -> dict:
    p = _sessions_path()
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


def _save_sessions(sessions: dict) -> None:
    _sessions_path().write_text(
        json.dumps(sessions, indent=2, ensure_ascii=False), encoding="utf-8"
    )


def get_demo_run_id(job_id: str) -> Optional[str]:
    if not _enabled():
        return None
    return _load_sessions().get(job_id)


def find_playback(filename: str) -> Optional[Path]:
    """Return the most recent captured demo run dir that contains artifacts for filename.

    A run qualifies when it has 01_extraction/extracted.md AND
    02_auto_entities/entities_auto.json, meaning it was fully captured locally.
    Returns None when no usable run exists (live processing should be used instead).
    """
    s = _settings()
    if not s.demo_runs_dir.exists():
        return None
    stem = Path(filename).stem
    candidates = []
    for d in s.demo_runs_dir.iterdir():
        if not d.is_dir():
            continue
        meta_path = d / "run_meta.json"
        if not meta_path.exists():
            continue
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
        except Exception:
            continue
        if stem not in meta.get("label", ""):
            continue
        if (d / "01_extraction" / "extracted.md").exists() and \
           (d / "02_auto_entities" / "entities_auto.json").exists():
            candidates.append((meta.get("started_at", ""), d))
    if not candidates:
        return None
    candidates.sort(key=lambda x: x[0], reverse=True)
    return candidates[0][1]


def list_demo_runs() -> list[dict]:
    """Return all demo runs, newest first."""
    s = _settings()
    if not s.demo_runs_dir.exists():
        return []
    runs = []
    for d in s.demo_runs_dir.iterdir():
        if not d.is_dir():
            continue
        meta_path = d / "run_meta.json"
        if meta_path.exists():
            try:
                runs.append(json.loads(meta_path.read_text(encoding="utf-8")))
            except Exception:
                pass
    runs.sort(key=lambda r: r.get("started_at", ""), reverse=True)
    return runs


def start_demo_run(job_id: str, label: str = "") -> str:
    """Create a new demo run attached to job_id. Returns demo_run_id."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    demo_run_id = f"demo_{ts}"
    s = _settings()
    run_dir = s.demo_runs_dir / demo_run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    meta = {
        "demo_run_id": demo_run_id,
        "job_id":      job_id,
        "label":       label,
        "started_at":  _now(),
        "status":      "active",
    }
    (run_dir / "run_meta.json").write_text(
        json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    sessions = _load_sessions()
    sessions[job_id] = demo_run_id
    _save_sessions(sessions)
    return demo_run_id


def stop_demo_run(job_id: str) -> None:
    """Detach demo capture from a job without deleting artifacts."""
    sessions = _load_sessions()
    sessions.pop(job_id, None)
    _save_sessions(sessions)


# ── Stage 01: Extraction ──────────────────────────────────────────────────────

def capture_extraction(job_id: str, job: Any, pdf_bytes: Optional[bytes] = None) -> None:
    """Save: input.pdf, extracted.md, extraction_meta.json."""
    run_id = get_demo_run_id(job_id)
    if not run_id:
        return
    try:
        s = _settings()
        stage_dir = s.demo_runs_dir / run_id / "01_extraction"
        stage_dir.mkdir(parents=True, exist_ok=True)

        # Input PDF — prefer from data/input/, fall back to raw bytes
        pdf_path = s.input_dir / job.filename
        if pdf_path.exists():
            shutil.copy2(pdf_path, stage_dir / "input.pdf")
            pdf_sha = _sha256_path(pdf_path)
        elif pdf_bytes:
            (stage_dir / "input.pdf").write_bytes(pdf_bytes)
            pdf_sha = _sha256_bytes(pdf_bytes)
        else:
            # try demo dir
            demo_path = s.demo_dir / job.filename
            if demo_path.exists():
                shutil.copy2(demo_path, stage_dir / "input.pdf")
                pdf_sha = _sha256_path(demo_path)
            else:
                pdf_sha = ""

        # Extracted markdown
        if getattr(job, "extracted_md", None):
            src = s.jobs_dir.parent / job.extracted_md
            if src.exists():
                shutil.copy2(src, stage_dir / "extracted.md")

        meta: dict = {
            "captured_at": _now(),
            "job_id":      job_id,
            "filename":    job.filename,
            "src_lang":    job.src_lang,
            "tgt_lang":    getattr(job, "tgt_lang", ""),
            "status":      str(job.status),
            "error":       getattr(job, "error", None),
            "input_sha256": pdf_sha,
        }
        (stage_dir / "extraction_meta.json").write_text(
            json.dumps(meta, indent=2, ensure_ascii=False, default=str),
            encoding="utf-8",
        )
    except Exception as exc:
        import logging
        logging.getLogger(__name__).warning("demo_capture.capture_extraction failed: %s", exc)


# ── Stage 02: Auto entities ───────────────────────────────────────────────────

def capture_auto_entities(job_id: str, job: Any) -> None:
    """Save entity list immediately after auto-detection (before manual review)."""
    run_id = get_demo_run_id(job_id)
    if not run_id:
        return
    try:
        s = _settings()
        stage_dir = s.demo_runs_dir / run_id / "02_auto_entities"
        stage_dir.mkdir(parents=True, exist_ok=True)

        entities = [
            (e.model_dump() if hasattr(e, "model_dump") else dict(e))
            for e in job.entities
        ]
        snapshot = {
            "captured_at": _now(),
            "job_id":      job_id,
            "count":       len(entities),
            "entities":    entities,
        }
        (stage_dir / "entities_auto.json").write_text(
            json.dumps(snapshot, indent=2, ensure_ascii=False, default=str),
            encoding="utf-8",
        )

        # Simple annotated preview markdown
        if getattr(job, "extracted_md", None):
            src = s.jobs_dir.parent / job.extracted_md
            if src.exists():
                _write_entity_preview(
                    src.read_text(encoding="utf-8"),
                    entities,
                    stage_dir / "reviewed_preview_auto.md",
                )
    except Exception as exc:
        import logging
        logging.getLogger(__name__).warning("demo_capture.capture_auto_entities failed: %s", exc)


# ── Stage 03: Entity event log ────────────────────────────────────────────────

def log_entity_event(
    job_id: str,
    action: str,
    entity_id: str,
    old_label: str = "",
    new_label: str = "",
    old_offsets: tuple = (),
    new_offsets: tuple = (),
    source: str = "manual",
    safe_display: str = "",   # stable token or label — never raw PHI
) -> None:
    """Append one entity action event to entity_events.jsonl."""
    run_id = get_demo_run_id(job_id)
    if not run_id:
        return
    try:
        s = _settings()
        stage_dir = s.demo_runs_dir / run_id / "03_manual_review"
        stage_dir.mkdir(parents=True, exist_ok=True)

        event: dict = {
            "timestamp":    _now(),
            "action":       action,   # add|delete|relabel|approve|reject|edit_text|approve_all
            "entity_id":    entity_id,
            "old_label":    old_label,
            "new_label":    new_label,
            "old_offsets":  list(old_offsets) if old_offsets else [],
            "new_offsets":  list(new_offsets) if new_offsets else [],
            "source":       source,
            "safe_display": safe_display,  # e.g. "[PATIENT_NAME_001]" or label
        }
        with (stage_dir / "entity_events.jsonl").open("a", encoding="utf-8") as f:
            f.write(json.dumps(event, ensure_ascii=False, default=str) + "\n")
    except Exception as exc:
        import logging
        logging.getLogger(__name__).warning("demo_capture.log_entity_event failed: %s", exc)


def capture_review_final(job_id: str, job: Any) -> None:
    """Save final reviewed entity state and markdown after review is complete."""
    run_id = get_demo_run_id(job_id)
    if not run_id:
        return
    try:
        s = _settings()
        stage_dir = s.demo_runs_dir / run_id / "03_manual_review"
        stage_dir.mkdir(parents=True, exist_ok=True)

        entities = [
            (e.model_dump() if hasattr(e, "model_dump") else dict(e))
            for e in job.entities
        ]
        snapshot = {
            "captured_at": _now(),
            "job_id":      job_id,
            "count":       len(entities),
            "entities":    entities,
        }
        (stage_dir / "entities_reviewed.json").write_text(
            json.dumps(snapshot, indent=2, ensure_ascii=False, default=str),
            encoding="utf-8",
        )

        md_field = getattr(job, "normalized_md", None) or getattr(job, "reviewed_md", None)
        if md_field:
            src = s.jobs_dir.parent / md_field
            if src.exists():
                shutil.copy2(src, stage_dir / "reviewed.md")

        # Public event log — structural metadata only, no safe_display
        _write_public_events(stage_dir)
    except Exception as exc:
        import logging
        logging.getLogger(__name__).warning("demo_capture.capture_review_final failed: %s", exc)


def _write_public_events(stage_dir: Path) -> None:
    """Write entity_events.public.jsonl — structural metadata, no PHI values."""
    src = stage_dir / "entity_events.jsonl"
    if not src.exists():
        return
    public_fields = {"timestamp", "action", "entity_id", "old_label", "new_label",
                     "old_offsets", "new_offsets", "source"}
    out_lines = []
    for line in src.read_text(encoding="utf-8").splitlines():
        try:
            event = json.loads(line)
            out_lines.append(
                json.dumps({k: v for k, v in event.items() if k in public_fields},
                           ensure_ascii=False)
            )
        except Exception:
            pass
    (stage_dir / "entity_events.public.jsonl").write_text(
        "\n".join(out_lines) + ("\n" if out_lines else ""), encoding="utf-8"
    )


# ── Stage 04: Export package ──────────────────────────────────────────────────

def capture_export_package(job_id: str, pkg_dir: Path, export_request: dict) -> None:
    """Copy Zone 2 safe export package files into the demo run folder."""
    run_id = get_demo_run_id(job_id)
    if not run_id:
        return
    try:
        s = _settings()
        stage_dir = s.demo_runs_dir / run_id / "04_export_package"
        stage_dir.mkdir(parents=True, exist_ok=True)

        _SAFE_EXTS = {".md", ".json", ".tmx", ".xliff", ".sdlxliff", ".docx", ".csv", ".zip"}
        for f in sorted(pkg_dir.iterdir()):
            if f.suffix in _SAFE_EXTS:
                shutil.copy2(f, stage_dir / f.name)

        # ZIP one level up (named {package_id}.zip)
        zip_path = pkg_dir.parent / f"{pkg_dir.name}.zip"
        if zip_path.exists():
            shutil.copy2(zip_path, stage_dir / "package.zip")

        (stage_dir / "export_request.json").write_text(
            json.dumps({"captured_at": _now(), **export_request},
                       indent=2, ensure_ascii=False, default=str),
            encoding="utf-8",
        )
    except Exception as exc:
        import logging
        logging.getLogger(__name__).warning("demo_capture.capture_export_package failed: %s", exc)


# ── Stage 05: Rehydration ─────────────────────────────────────────────────────

def capture_rehydration(
    job_id: str,
    input_content: bytes,
    input_filename: str,
    output_content: bytes,
    token_map: dict[str, str],
) -> None:
    """Save rehydration input/output and a structured report."""
    run_id = get_demo_run_id(job_id)
    if not run_id:
        return
    try:
        s = _settings()
        stage_dir = s.demo_runs_dir / run_id / "05_rehydration"
        stage_dir.mkdir(parents=True, exist_ok=True)

        ext = Path(input_filename).suffix
        (stage_dir / f"input_with_tokens{ext}").write_bytes(input_content)
        (stage_dir / f"rehydrated_output{ext}").write_bytes(output_content)

        # Token analysis (from text representation)
        try:
            input_text = input_content.decode("utf-8", errors="replace")
            found_tokens = set(_TOKEN_RE.findall(input_text))
            found_bracketed = {f"[{t}]" for t in found_tokens}
        except Exception:
            found_bracketed = set()

        replaced    = {t for t in token_map if t in found_bracketed}
        unresolved  = found_bracketed - set(token_map)

        report = {
            "captured_at":      _now(),
            "input_filename":   input_filename,
            "tokens_found":     sorted(found_bracketed),
            "tokens_replaced":  sorted(replaced),
            "unresolved_tokens": sorted(unresolved),
            "warnings":         sorted(unresolved),
            "input_sha256":     _sha256_bytes(input_content),
            "output_sha256":    _sha256_bytes(output_content),
        }
        (stage_dir / "rehydration_report.json").write_text(
            json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8"
        )
    except Exception as exc:
        import logging
        logging.getLogger(__name__).warning("demo_capture.capture_rehydration failed: %s", exc)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _write_entity_preview(text: str, entities: list[dict], out_path: Path) -> None:
    """Write an annotated markdown preview of auto-detected entities."""
    label_counts: dict[str, int] = {}
    for e in entities:
        lbl = e.get("label", "UNKNOWN")
        label_counts[lbl] = label_counts.get(lbl, 0) + 1

    lines = [
        "# Auto-Detected Entity Preview",
        "",
        f"*Total detected: {len(entities)}*",
        "",
        "| Label | Count |",
        "|-------|-------|",
    ]
    for lbl, cnt in sorted(label_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| `{lbl}` | {cnt} |")

    lines += ["", "---", "", text]
    out_path.write_text("\n".join(lines), encoding="utf-8")
